format_version: 10
pipelines:
  coucou-as-code:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-db9d3b7:
        git: https://github.com/nicoovh/gocdtest
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - test-and-report:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          run-unit-tasks:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - coucou
                command: echo
                run_if: passed
